services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: elearning-siswa:latest
    container_name: elearning-app
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./.env:/var/www/html/.env
    depends_on:
      - db
    networks:
      - elearning-network

  db:
    image: mysql:8.0
    container_name: elearning-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: elearning
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3315:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - elearning-network

networks:
  elearning-network:
    driver: bridge

volumes:
  db-data:
